version: '3.1'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: nginx
    volumes:
      - ./nginx_server.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ./:/var/www
    container_name: app
    networks:
      - mynetwork
    depends_on:
      - db

  
  db:
    image: mysql:5.7
    volumes:
      - ./mysql_data:/var/lib/mysql
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql_data: